from .face_filter_node import (
    NODE_CLASS_MAPPINGS as FF_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as FF_NAMES,
)
from .merge_batches_node import (
    NODE_CLASS_MAPPINGS as MB_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as MB_NAMES,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(FF_CLASSES)
NODE_CLASS_MAPPINGS.update(MB_CLASSES)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(FF_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(MB_NAMES)
